### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by nii236** [rohan-shah/residualConnectivity#1]
Dumb people like me want to know what you're doing! 

- Add README.md

**Comment by rohan-shah** [comment]
What, you mean folder names like gridCountSpecificSize2 aren't self explanatory? Damn.

**Comment by nii236** [comment]
This issue is now closed due to @rohan-shah 's apparently self explanatory folder names.

**Comment by rohan-shah** [comment]
....README.md is coming tomorrow, I swear.

**Comment by nii236** [comment]
Thanks!
